name: code analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install pylint
      run: pip install pylint
    - uses: cclauss/GitHub-Action-for-pylint@0.7.0   
    - name: GitHub Action for pylint
     
      run : pylint 3_Implementation/
    #- name: code_analysis
     # run: pylint ./3_Implementation/
   #- name: GitHub Action for pylint
   #uses: cclauss/GitHub-Action-for-pylint@0.7.0
