name: C/C++ CI Ubuntu- Build Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ubuntu_build
      run: python 3_Implementation/test/test.py